
insert into member_tb (email, password, roles) values ('admin@admin.com', '{bcrypt}$2a$10$MAjh7dKPLYYRXafeBc.Pt.tY41e/gTV6YRNPpqS2nQTiO.tH4s4IS', 'ROLE_MEMBER');
insert into member_tb (email, password, roles) values ('taffleck1@miitbeian.gov.cn', 'oE9/?O\7A||S', 'ROLE_MEMBER');
insert into member_tb (email, password, roles) values ('astrotton2@themeforest.net', 'hY8}rb_AK4', 'ROLE_MEMBER');
insert into member_tb (email, password, roles) values ('zfeake3@reuters.com', 'pA8/K=.d2aS.XO"', 'ROLE_MEMBER');
insert into member_tb (email, password, roles) values ('kyeliashev4@addthis.com', 'gF0!kQK>S%\!', 'ROLE_MEMBER');
insert into member_tb (email, password, roles) values ('dwibberley5@patch.com', 'qU1"Hplle', 'ROLE_MEMBER');
insert into member_tb (email, password, roles) values ('cderechter6@google.it', 'vQ4%H_UZ', 'ROLE_MEMBER');
insert into member_tb (email, password, roles) values ('hraiker7@eventbrite.com', 'mL2''>1&T$6SC`U<Y', 'ROLE_MEMBER');
insert into member_tb (email, password, roles) values ('vshillitoe8@house.gov', 'xA7*YjSqgQU?FV', 'ROLE_MEMBER');
insert into member_tb (email, password, roles) values ('lthunnerclef9@reverbnation.com', 'wT7`\X7..ovIIEC', 'ROLE_MEMBER');

insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Basil - Pesto Sauce', 'description', 243305);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Vinegar - Cider', 'description', 808254);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Green Tea Refresher', 'description', 286066);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Seedlings - Mix, Organic', 'description', 550715);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Cahors Ac 2000, Clos', 'description', 823323);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Radish - Pickled', 'description', 425595);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Carbonated Water - Orange', 'description', 172285);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Muffin - Mix - Mango Sour Cherry', 'description', 827968);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Flour - Semolina', 'description', 623954);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Skewers - Bamboo', 'description', 211133);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cheese - Parmesan Grated', 'description', 790092);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Squeeze Bottle', 'description', 814525);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Steel Wool', 'description', 688301);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Tray - 16in Rnd Blk', 'description', 772744);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Chicken - Leg, Fresh', 'description', 683693);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Marsala - Sperone, Fine, D.o.c.', 'description', 232065);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Muffin Batt - Blueberry Passion', 'description', 498024);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Lid - High Heat, Super Clear', 'description', 892536);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cheese - Wine', 'description', 105581);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Champagne - Brights, Dry', 'description', 466048);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Pork Loin Cutlets', 'description', 82117);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Yogurt - Blueberry, 175 Gr', 'description', 746634);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Syrup - Monin - Granny Smith', 'description', 610352);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Sage - Fresh', 'description', 380429);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Potatoes - Pei 10 Oz', 'description', 75126);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Zucchini - Yellow', 'description', 842763);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Beer - Rickards Red', 'description', 956841);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Sprouts Dikon', 'description', 425719);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Lettuce - Boston Bib - Organic', 'description', 135992);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Stock - Fish', 'description', 729090);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cranberries - Fresh', 'description', 356157);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bread Ww Cluster', 'description', 833279);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Chicken Breast Wing On', 'description', 518472);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Beer - Blue Light', 'description', 374626);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cheese - La Sauvagine', 'description', 120788);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Compound - Orange', 'description', 426122);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Scampi Tail', 'description', 368985);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cauliflower', 'description', 721361);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bread - Bagels, Mini', 'description', 250735);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Towel - Roll White', 'description', 933007);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cheese - Brie Roitelet', 'description', 871642);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Pork - Bones', 'description', 472891);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Icecream - Dstk Super Cone', 'description', 734964);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bread - Roll, Calabrese', 'description', 807847);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Salmon - Whole, 4 - 6 Pounds', 'description', 849200);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Muffin - Banana Nut Individual', 'description', 533036);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Chocolate Bar - Smarties', 'description', 128977);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wiberg Super Cure', 'description', 586363);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Chicken - Livers', 'description', 533250);
insert into product (image, product_name, description, price) values ('filepath/UUID/fileName', 'Salt And Pepper Mix - Black', 'description', 530386);
